listening-port=3478
listening-ip=0.0.0.0
min-port=49160
max-port=49200
fingerprint
realm=turn.web3-chat.local
lt-cred-mech
user=chatuser:230f0dae70e9e406539759bf970b481f
external-ip=47.109.17.166

# If you run on Docker bridge instead of host networking:
# Replace these with your real values before production.
# external-ip=<PUBLIC_IP>/<DOCKER_BRIDGE_IP>
# relay-ip=<DOCKER_BRIDGE_IP>

no-cli
no-tls
no-dtls
stale-nonce=600
simple-log
log-file=stdout
